# Generated by Django 3.2.7 on 2021-09-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='incentives',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
